services:
  - type: web
    name: sigmagpt-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --legacy-peer-deps --omit=dev
    startCommand: node server.js
    rootDir: Backend
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: MONGODB_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
    autoDeploy: true